'use client'

import { useState, useMemo } from 'react'
import { FileText, Download, Eye, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Checkbox } from '@/components/ui/checkbox'
import { SeverityBadge } from '@/components/findings/SeverityBadge'
import { StatusBadge } from '@/components/findings/StatusBadge'
import type { Finding } from '@/lib/types'

type TemplateId = 'h1' | 'bugcrowd' | 'intigriti' | 'synack' | 'generic'

const templates: { id: TemplateId; name: string; description: string }[] = [
  { id: 'h1', name: 'HackerOne', description: 'Standard HackerOne report format' },
  { id: 'bugcrowd', name: 'Bugcrowd', description: 'Bugcrowd VRT-aligned format' },
  { id: 'intigriti', name: 'Intigriti', description: 'Intigriti submission format' },
  { id: 'synack', name: 'Synack', description: 'Synack Red Team format' },
  { id: 'generic', name: 'Generic', description: 'Generic security advisory format' },
]

function generateReport(findings: Finding[], template: TemplateId, extra: { title: string; summary: string; remediation: string }): string {
  const title = extra.title || 'Security Vulnerability Report'
  const separator = '─'.repeat(60)

  let report = `# ${title}\n\n`
  report += `**Template:** ${templates.find((t) => t.id === template)?.name || 'Generic'}\n`
  report += `**Date:** ${new Date().toISOString().split('T')[0]}\n`
  report += `**Findings:** ${findings.length}\n\n`
  report += `${separator}\n\n`

  if (extra.summary) {
    report += `## Summary\n\n${extra.summary}\n\n${separator}\n\n`
  }

  report += `## Vulnerability Details\n\n`

  findings.forEach((f, i) => {
    report += `### ${i + 1}. ${f.title}\n\n`
    report += `| Field | Value |\n`
    report += `|-------|-------|\n`
    report += `| **Severity** | ${f.severity.toUpperCase()} |\n`
    report += `| **Status** | ${f.status.replace('_', ' ').toUpperCase()} |\n`
    report += `| **CVE** | ${f.cveId || 'N/A'} |\n`
    report += `| **CVSS** | ${f.cvssScore != null ? f.cvssScore.toFixed(1) : 'N/A'} |\n`
    report += `| **Tool** | ${f.tool || 'Manual'} |\n`
    report += `| **Found** | ${new Date(f.foundAt).toISOString().split('T')[0]} |\n\n`

    if (f.description) {
      report += `**Description:**\n${f.description}\n\n`
    }
    if (f.request || f.response) {
      report += `**Evidence:**\n\n`
      if (f.request) {
        report += "```http\n" + f.request + "\n```\n\n"
      }
      if (f.response) {
        report += "```http\n" + f.response + "\n```\n\n"
      }
    }
    report += `${separator}\n\n`
  })

  if (extra.remediation) {
    report += `## Remediation\n\n${extra.remediation}\n\n${separator}\n\n`
  }

  report += `*Report generated by BountyOS on ${new Date().toISOString()}*\n`

  return report
}

interface ReportBuilderProps {
  findings: Finding[]
  onGenerate?: (report: string) => void
}

export function ReportBuilder({ findings, onGenerate }: ReportBuilderProps) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [template, setTemplate] = useState<TemplateId>('h1')
  const [title, setTitle] = useState('')
  const [summary, setSummary] = useState('')
  const [remediation, setRemediation] = useState('')
  const [preview, setPreview] = useState(false)

  const selectedFindings = findings.filter((f) => selectedIds.has(f.id))

  function toggleFinding(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  function selectAll() {
    if (selectedIds.size === findings.length) setSelectedIds(new Set())
    else setSelectedIds(new Set(findings.map((f) => f.id)))
  }

  const reportContent = useMemo(
    () => generateReport(selectedFindings, template, { title, summary, remediation }),
    [selectedFindings, template, title, summary, remediation]
  )

  function handleGenerate() {
    onGenerate?.(reportContent)
    setPreview(true)
  }

  async function handleDownload() {
    const blob = new Blob([reportContent], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${title || 'report'}-${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div className="space-y-6">
        <div className="card p-6 space-y-4">
          <h3 className="text-lg font-bold text-text-primary flex items-center gap-2">
            <FileText className="w-5 h-5" /> Report Builder
          </h3>

          <div className="space-y-2">
            <Label htmlFor="template">Template</Label>
            <Select value={template} onValueChange={(v) => setTemplate(v as TemplateId)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {templates.map((t) => (
                  <SelectItem key={t.id} value={t.id}>
                    {t.name} — {t.description}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="title">Report Title</Label>
            <Input id="title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Security Vulnerability Report" />
          </div>

          <div className="space-y-2">
            <Label htmlFor="summary">Executive Summary</Label>
            <Textarea id="summary" value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Brief overview of findings..." rows={3} />
          </div>

          <div className="space-y-2">
            <Label htmlFor="remediation">Remediation Advice</Label>
            <Textarea id="remediation" value={remediation} onChange={(e) => setRemediation(e.target.value)} placeholder="Recommended fixes..." rows={3} />
          </div>
        </div>

        <div className="card p-6 space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-semibold text-text-primary">Select Findings ({selectedIds.size})</h4>
            <label className="flex items-center gap-2 text-xs text-text-muted cursor-pointer">
              <Checkbox checked={selectedIds.size === findings.length && findings.length > 0} onCheckedChange={selectAll} />
              Select All
            </label>
          </div>
          <div className="max-h-[400px] overflow-y-auto space-y-1">
            {findings.map((f) => (
              <label
                key={f.id}
                className={`flex items-center gap-3 px-3 py-2 rounded text-sm cursor-pointer transition-colors ${
                  selectedIds.has(f.id) ? 'bg-bg-elevated' : 'hover:bg-bg-surface'
                }`}
              >
                <Checkbox checked={selectedIds.has(f.id)} onCheckedChange={() => toggleFinding(f.id)} />
                <SeverityBadge severity={f.severity} size="sm" />
                <span className="flex-1 text-text-primary truncate">{f.title}</span>
                <StatusBadge status={f.status} />
              </label>
            ))}
            {findings.length === 0 && (
              <p className="text-sm text-text-muted text-center py-4">No findings available</p>
            )}
          </div>
        </div>

        <div className="flex gap-3">
          <Button onClick={handleGenerate} disabled={selectedFindings.length === 0} className="flex-1">
            <RefreshCw className="w-4 h-4 mr-1" /> Generate Report
          </Button>
          <Button variant="outline" onClick={handleDownload} disabled={!preview}>
            <Download className="w-4 h-4 mr-1" /> Download MD
          </Button>
        </div>
      </div>

      <div>
        {preview ? (
          <div className="card">
            <div className="px-4 py-3 border-b border-border flex items-center gap-2">
              <Eye className="w-4 h-4 text-text-muted" />
              <span className="text-sm font-semibold text-text-primary">Preview</span>
            </div>
            <div className="p-4 overflow-auto max-h-[700px]">
              <pre className="text-xs font-mono text-text-secondary whitespace-pre-wrap">{reportContent}</pre>
            </div>
          </div>
        ) : (
          <div className="card p-12 text-center">
            <FileText className="w-10 h-10 text-text-muted mx-auto mb-3" />
            <p className="text-sm text-text-muted">Select findings and generate a report to see preview</p>
          </div>
        )}
      </div>
    </div>
  )
}
